### ISSUE TITLE
How to improve download speeds?

### ISSUE THREAD

**Issue by JoaGamo** [divyam234/teldrive#197]
Hello, I've added 9 bots and through the UI I can't get more than 3MB/s download speed, how could I get more performance out of it? I've increased --tg-bg-bots-limit to 9 but can't get any more out of it.
I'm also using teldrive's rclone with rclone mount but I get the same speed.

**Comment by bolavefasfas** [comment]
Try rclone will give 2x speed if  our familir with cli usage.

**Comment by JoaGamo** [comment]
I couldn't find the proper parameter I should add to my rclone syntax

I'm using this (do note that im using the rclone modified by the author to support teldrive)
/root//rclone/rclone mount teldrive: /mnt/teldrive/ --allow-other --umask 000 --vfs-cache-mode full --vfs-cache-max-age 2h --vfs-cache-max-size 300G --vfs-fast-fingerprint --buffer-size 1G --vfs-read-ahead 1G --vfs-read-chunk-size 250M --vfs-cache-poll-interval 10s --transfers 16 --multi-thread-streams 4 --low-level-retries 3 --cache-dir /hdd/ &

I've been testing with --transfers up and down, but I couldn't get a higher download performance

**Comment by azeyrx** [comment]
Teldrive is perfect for running on a server, this server should have a good connection to the Netherlands, because that's where the API servers are located... In general, EU servers offer the best speeds to Telegram (own "investigation").

In addition, no file encryption should be active, as this eats up a lot of performance and therefore also speed.

Use a local cache to store some data locally to avoid downloading it again. Unfortunately, the bots cause problems for me personally, but I don't know why - sometimes they throw out random 500 errors.

Translated with DeepL.com (free version)

**Comment by azeyrx** [comment]
Teldrive is perfect for running on a server, this server should have a good connection to the Netherlands, because that's where the API servers are located... In general, EU servers offer the best speeds to Telegram (own "investigation").

In addition, no file encryption should be active, as this eats up a lot of performance and therefore also speed.

Use a local cache to store some data locally to avoid downloading it again. Unfortunately, the bots cause problems for me personally, but I don't know why - sometimes they throw out random 500 errors.

**Comment by JoaGamo** [comment]
I'm experiencing more notably this issue with single big files, rclone won't send multiple read requests and it makes it so slow, as only one bot is working per part
I expected that when I download a single file with 9 parts, all 9 bots would download one part in parallel for fastest speed. I thought it could be a problem with my rclone syntax, but with teldrive's UI the same problem happens.

ps: I have a dedicated server and in my syntax i'm running a vfs full-cache

**Comment by aniel300** [comment]
am having the same issue

**Comment by truongbber** [comment]
does adding bots increase download speed, or what is the purpose of adding more bots, can't find any tutorial related to this
