### ISSUE TITLE
Neontech DB increasing size

### ISSUE THREAD

**Issue by Xabiman** [divyam234/teldrive#244]
Hi! I noticed my Neontech DB data size is increasing with no uploads (more than 1 mb/hour)... In some days size will be more than 512 mb allowed at the free subscription. Do you know how to solve it and why this increase? I've seen at Neon monitoring that periodically rows are updated and every row updated get a DB increase. If I stop Teldrive then there aren't updates and the DB doesn't grow up, so this increasing is created by Teldrive. Any help with this or anyway to solve?

**Comment by steffen-poulsen** [comment]
The free Neon tier will only work for a very limited number of files.

I'm not sure what might be causing your database to grow, it is not a pattern that I am seeing.

Anyway, the way forward is to run the postgresql instance locally instead of using Neon. SaddyTech is showing [one way of doing it](https://www.youtube.com/watch?v=DR9rN9xAN6A), or you can follow the docker compose instructions from the docs.
