### ISSUE TITLE
[BUG] Missing files in listing if there is a large amount of sub dirs/files

### ISSUE THREAD

**Issue by vavtnen** [divyam234/teldrive#284]
Running 1.4.5 binary.

Files are missing if there are large mount of sub dirs/files (1500+ dirs and 1000+ files) from listing. This happens when mounted with rclone and the webui. 

During my test, files will show up if I limited the number of sub dirs in a dir. This doesn't happens if a dir consist of only dirs or only files.

My be it is related to this [#238](https://github.com/divyam234/teldrive/issues/238)

**Comment by Linden10** [comment]
Ah I thought this bug was not going to return that I was considering closing my issue but I guess it's still exists! Do you have the newest version of rclone btw?

Also this is interesting, not only are you missing files in a mount but also in web-ui too? I never expereicned that problem before, do note that files and folders in web-ui show only the first 500 and increase as you scroll down, however you can change that in the options of the web-ui to show more files at a time.

However if despite that the files/folders appearing are still missing in mount/web ui (even after scrolling all the way down)...then this is a new crazy bug alright!

Which reminds me, for me I was able to somehow resolve the bug by running the same rclone copy command that I used to upload the files originally over and over again, while also running rclone check in between each upload to compare the files of my mount to the source dir that I uploaded my files/folders from to see if the missing files/folders are still there until they're not!

It's the only thing that resolved the issue for me, however mysterious it was resolved...
